name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: './ToolKit'
            exclude: ''
          - check: './Editor'
            exclude: '(ImGui)'
          - check: './Import'
            exclude: '(assimp|stb_)'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.8.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Microsoft' # optional